### ISSUE TITLE
isPw method, TypeError: Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by jochongs** [Stageus-Corp/validator#5]
message().isString().isPw().run('aaaaaaasdf');

```
if (option.number !== false) {
               ^

TypeError: Cannot read properties of undefined (reading 'number')
    at Task.isPw [as method] (/Users/jochong/stageus/library/@stageus/validator/dist/method/validate/string/isPw.js:17:16)
    at StringValidator.run (/Users/jochong/stageus/library/@stageus/validator/dist/class/validate/Validator.js:17:33)
    at Object.<anonymous> (/Users/jochong/stageus/library/@stageus/validator/dist/index.js:56:42)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.0
```
maybe optional parameter type error

**Comment by jochongs** [comment]
fix bug

#8
